### ISSUE TITLE
Issue with default behaviour on Knapsack example

### ISSUE THREAD

**Issue by davage** [dwave-examples/knapsack#4]
Opening a new Knapsack example and hitting the green play button gives results that do not satisfy the maximum weight constraint out of the box.

**Comment by sploiber** [comment]
Please see the pull request. The last loop needed to be much smarter - not to assume any particular ordering of the keys in the returned bitstring.
This explains why it worked in the small case, but not the large case.
Once there are 10, an alphabetic ordering yields
0, 1, 10....
and the objects/weights got confused.
